canal.instance.mysql.slaveId=1234
canal.instance.master.address=mysql8:3306

# MySQL 账号密码
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset=UTF-8

# 监听的数据库和表，.*\\..* 表示所有库所有表
canal.instance.filter.regex=.*\\..*
